name: Deployment
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build
        run: mkdir -p dist && echo "Hello World" > dist/index.html
        
      - uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 使用系统自动生成的token
          branch: gh-pages
          folder: dist
