name: Deployment
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          mkdir -p dist
          echo "<!DOCTYPE html>
          <html>
          <body>
          <h1>部署验证 $(date)</h1>
          <p>User-Agent: <span id='ua'></span></p>
          <script>
            document.getElementById('ua').textContent = navigator.userAgent;
          </script>
          </body>
          </html>" > dist/index.html
          touch dist/.nojekyll  # 关键文件

      - uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist
          clean: true
          clean-exclude: |
            .nojekyll
            CNAME
          dotfiles: true
